permalink: /:categories/:title.html
auto: true
description: "Software Architect in Web Development World"
keywords:
 - Software Architect
 - Web Developer
 - CakePHP Developer
main_title: "Lubomír Štork"
